# Generated by Django 2.2 on 2020-05-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
