# Generated by Django 2.2 on 2020-05-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200521_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allthreads',
            new_name='allthread',
        ),
    ]
