# Generated by Django 2.2 on 2020-05-21 09:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200521_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
