# Generated by Django 2.2 on 2020-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200521_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select Your Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
    ]
